### ISSUE TITLE
Nominal argument examples

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-ontology#38]
# reported by Richard during a team meeting

`fight-A` 

<img width="1370" alt="image" src="https://github.com/presciencelabs/tabitha-ontology/assets/4412848/25c23506-3cc4-4a4a-ac2e-f6ed43b7b071">

These examples represent the words (so far) that have been used in each of the Theta Grid sections...

1. Need to see if this data is available in the db or is derived on TBTA bootstrap.
2. Consider some UX/UD to make this available to the users.

**Comment by craigp-atw** [comment]
These are drawn directly from the Exhaustive Examples, but instead of showing all the roles for a particular verse (which is how the data is organized), it shows all the nouns that appear in a particular role, taken from each example.

**Comment by craigp-atw** [comment]
It would probably be best to put these below the `Examples` section, and show them in a format similar to what TBTA does. Also note that TBTA only shows the first 25 examples, so we could limit the number as well.

**Comment by longrunningprocess** [comment]
accidentally duped #51 , notes from that one:

# from Richard

> In the TBTA program, you can see the nouns that have been used for certain semantic roles for a verb. For instance, I could look up "say-A" in the ontology, hover the mouse over the theta grid column. And see that John, David, Saul, etc... have been used for the agent. Billy, it would be nice if we could see this kind of information in the online ontology. Thanks


Perhaps a word cloud, or filters per semantic role... not sure of the best treatment yet:

https://ontology.tbta.bible/?q=say-A&category=all&scope=stems

![image](https://github.com/user-attachments/assets/bad3189f-5035-40e5-9531-ac714eeb243e)

![image](https://github.com/user-attachments/assets/e81966a8-e94d-4546-8922-9acd50acc645)

**Comment by craigp-atw** [comment]
This will be resolved with the `use-new-examples-format` because the filter dropdowns show all concepts that were used in a specific role. See below.

![image](https://github.com/user-attachments/assets/dcde57c5-6c6e-45ec-b0dc-87b6536a6aa8)
