### ISSUE TITLE
Filter how-to results by part-of-speech

### ISSUE THREAD

**Issue by craigp-atw** [presciencelabs/tabitha-ontology#42]
From Mikayla:
> I noticed that "bow" Noun in the ontology borrowed the information from "bow" verb in the How-to. Is there a way for it to see that second column so it only applies suggestion for the correct part of speech?

![image](https://github.com/presciencelabs/tabitha-ontology/assets/152427351/afd2e8a0-c8dc-4f25-91eb-7a9099e7cc80)

**Comment by longrunningprocess** [comment]
also received a request from the team today to see all words for a given part of speech...

I'm wondering about a UI with a dynamic part of speech icon(button) bar similar to the view toggle:

![image](https://github.com/presciencelabs/tabitha-ontology/assets/4412848/af62fbcc-faad-4810-a294-5d46bb538cbe)

that would allow the parts of speech represented by the returned results to be clicked to narrow the results down to just those buttons selected...

[ Noun ] [ Verb ] [ Adposition* ] [ Particle* ]...

**Comment by craigp-atw** [comment]
Resolved in #45
