### ISSUE TITLE
part of speech filter for results

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-ontology#44]
received a request from the team today to see all words for a given part of speech...

I'm wondering about a UI with a dynamic part of speech icon(button) bar similar to the view toggle:

![image](https://github.com/presciencelabs/tabitha-ontology/assets/4412848/af62fbcc-faad-4810-a294-5d46bb538cbe)

that would allow the parts of speech represented by the returned results to be clicked to narrow the results down to just those buttons selected...

[ Noun ] [ Verb ] [ Adposition* ] [ Particle* ]...

ref:  https://daisyui.com/components/join/#join-radio-inputs-with-btn-style

buttons that are selected would simply apply filters to the underlying "results"

_Originally posted by @longrunningprocess in https://github.com/presciencelabs/tabitha-ontology/issues/42#issuecomment-2204095167_

**Comment by craigp-atw** [comment]
I started trying to support selecting multiple parts of speech, but it requires more complexity. I'm not sure what the use case is of being able to select multiple parts of speech, so I opted for the simpler approach of only allowing one.

**Comment by longrunningprocess** [comment]
![image](https://github.com/presciencelabs/tabitha-ontology/assets/4412848/6154396d-6b85-4712-a830-b9fc574adf20)

the way this is working right now makes me reconsider it a bit... in its current implementation, I think it would actually be quite natural to simply add it right next to the existing "Stems only" dropdown.
