### ISSUE TITLE
Overlay examples on Theta Grid

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-ontology#7]
every reference could be overlaid on a "grid", checkout the app: TBTA->Ontology-><word>->right-click->"Edit this concept's collocation...":  

`Agent | Patient | State | Source | Destination | Instrument | Beneficiary | Patient prop | Participant prop`

some good words to exercise any display algorithm for overlaying verse contents in a "grid":

- knowB (verb) [Agent-like(Instrument)Patient proposition]
- takeA (verb) [Agent-likePatient-like(Source)(Destination)(Instrument)]
- writeA (verb) [Agent-likePatient-like(Source)(Destination)(Instrument)(Beneficiary)]
- ableA (adj)
- goodA (adj)

The encoding for exhaustive examples (for VERBS in the Ontology) map directly to the grid above:

`Judges 14:9 => p|A|SamsonA|honeyA||beeA||handA|||`

| Agent   | Patient | State | Source | Destination | Instrument | Beneficiary | Patient prop | Participant prop |
|---------|---------|-------|--------|-------------|------------|-------------|--------------|------------------|
| SamsonA | honeyA  |       | beeA   |             | handA      |             |              |                  |

# mock-up
![image](https://github.com/presciencelabs/tabitha-ontology/assets/4412848/e27fd7e6-bf84-4a04-a4f6-118a6e02d5a9)

**Comment by craigp-atw** [comment]
This overlay can be placed on the dropdown for each example, replacing the text shown below:
![image](https://github.com/user-attachments/assets/3a9998e5-f1e5-4803-8262-902c8a552d7a)

That text is essentially a minimal attempt to arrange the arguments in a readable way. Using a grid instead is better visually.

**Comment by craigp-atw** [comment]
This will be resolved with the `use-new-examples-format` because the context/arguments are shown in a labelled badge. See below.

![image](https://github.com/user-attachments/assets/ffc02648-47ad-4f3f-a344-19937dc54513)
