### ISSUE TITLE
Permutations dropdown for examples

### ISSUE THREAD

**Issue by longrunningprocess** [presciencelabs/tabitha-ontology#8]
when working out the display for references, consider organizing them by specific permutations, e.g., examples with an instrument, examples without, by book...

1. need to consider what to do about duplicate chapter:verse keys, e.g., takeA Exodus 21:24
2. add permutations dropdown once the algorithm is worked out

> `Judges 14:9 => p|A|SamsonA|honeyA||beeA||handA|||`

`| Agent-like | Patient-like | (Source) | (Destination) | (Instrument) |` => **2^3 permutations**

|         |         |       |             |            | Heading        |
|---------|---------|-------|-------      |-------     |----------------|
| Agent   | Patient |       |             |            | with required only  |
| Agent   | Patient | Source|             |            | with Source |
| Agent   | Patient | Source| Destination |            | with Source and Destination |
| Agent   | Patient | Source| Destination | Instrument | with Source, Destination and Instrument |           
| Agent   | Patient | Source|             | Instrument | with Source and Instrument |
| Agent   | Patient |       | Destination |            | with Destination |
| Agent   | Patient |       | Destination | Instrument | with Destination and Instrument |
| Agent   | Patient |       |             | Instrument | with Instrument |

**Comment by longrunningprocess** [comment]
I wonder if it makes sense to bring the theta grid out of the main card area and put it under the Examples header... ask some of the users if the theta grid is useful in the "summary" or more applicable in the "details".

**Comment by craigp-atw** [comment]
After discussion, we decided to try adding a multi-selector (eg checkboxes) for each role of the theta grid above the verse dropdowns - so selecting 'Destination' would cause the dropdowns to only include the examples that contain a 'Destination' argument.

Selecting multiple roles would likely act as an `AND` filter, but that's not certain.

**Comment by craigp-atw** [comment]
This will be resolved with the new example filtering system. Selecting 'Present'/'Not present' for various combination of arguments is the same functionality desired in this issue.
